config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :questions

  namespace :quiz_mode do
    resources :questions, only: :show do
      resources :answer, only: :index
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :content, presence: true
  validates :answer, presence: true

  def correct?(answer_to_confirm)
    return true if same_with_answer?(answer_to_confirm)
    number = convert_words_to_numbers(answer_to_confirm)
    return same_with_answer?(number) if number.present?
    false
  end

  def self.random
    find(pluck(:id).sample)
  end

  private

  def same_with_answer?(answer_to_confirm)
    answer == answer_to_confirm
  end

  def convert_words_to_numbers(answer_to_confirm)
    # NumberInWords.in_numbers returns 0 when it receives a value that can not be converted
    return '0' if answer_to_confirm == 'zero'
    number = NumbersInWords.in_numbers(answer_to_confirm)
    # if this number here is 0, answer is unconvertible value
    return nil if number.zero?
    number.to_s
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show; end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit; end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_url, success: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to questions_url, success: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, success: 'Question was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:content, :answer)
  end
end

app/controllers/quiz_mode/answer_controller.rb
# frozen_string_literal: true

module QuizMode
  class AnswerController < ApplicationController
    def index
      question = Question.find(params[:question_id])
      render json: { answer: question.answer }
    end
  end
end

app/controllers/quiz_mode/questions_controller.rb
# frozen_string_literal: true

module QuizMode
  class QuestionsController < ApplicationController
    def index
      @questions = Question.all
    end

    def show
      return render json: { result: quiz_result } if quiz_result_mode?

      respond_to do |format|
        format.html
        format.json { set_question }
      end
    end

    private

    def set_question
      @question = params[:id] == 'random' ? Question.random : Question.find(params[:id])
    end

    def quiz_result
      Question.find(params[:id]).correct?(params[:answer])
    end

    def quiz_result_mode?
      params[:answer].present? && params[:id] != 'random'
    end
  end
end

app/views/home/index.html.erb
<div class="intro mt-4">
  <h1 class="text-center">Quiz Master</h1>
  <p class="text-center">Please choose whether to try or edit quizzes</p>
</div>
<div class="d-flex justify-content-center buttons">
  <%= link_to "Quiz Mode", quiz_mode_question_path('random'), { class: "btn btn-primary" } %>
  <%= link_to "Manage Questions", questions_path, { class: "btn btn-light" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMaster</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-dark navbar-expand-lg bg-white portfolio-navbar gradient">
      <div class="container-fluid">
        <%= link_to "Quiz Master", root_path, { class: "navbar-brand logo" } %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item" role="presentation">
              <%= link_to "Quiz Mode", quiz_mode_question_path('random'), { class: "nav-link" } %>
            </li>
            <li class="nav-item" role="presentation">
              <%= link_to "Manage Questions", questions_path, { class: "nav-link" } %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> mt-2">
          <%= msg.html_safe %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :answer %>
    <%= form.text_field :answer, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h3 class="mb-4 mt-4">Editing Question</h3>

<%= render 'form', question: @question %>
<div class="mt-3">
<%= link_to 'Back', questions_path %>
<div>

app/views/questions/index.html.erb
<h3 class="mt-4">Question List</h3>

<%= link_to  new_question_path, class: "btn btn-primary mt-3" do %>
  <i class="fa fa-file-o mr-2"></i>
  Create New Question
<% end %>
<div class="table-responsive mt-4">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Question</th>
        <th>Answer</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td><%= question.id %></td>
          <td><%= question.content %></td>
          <td><%= question.answer %></td>
          <td>
            <%= link_to edit_question_path(question), class: "btn btn-primary" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/questions/new.html.erb
<h3 class="mb-4 mt-4">Create New Question</h3>

<%= render 'form', question: @question %>
<div class="mt-3">
  <%= link_to 'Back', questions_path %>
<div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/quiz_mode/questions/show.html.erb
<div id="AnswerApp"></div>
<%= javascript_pack_tag 'AnswerApp' %>